language: node_js
install: npm install
script:
  - node build.js --prod
  - bash deploy.sh
cache:
  directories:
  - node_modules
env:
  global:
    secure: WtIgU0PSiwmSekWqMSRtv29FEXp6liowDV0Y965FvUfwi+DpbYlcbCdB8rpvg768KAxoRQEknKAEsNbuLOucO3WM6Eag2Hcq8YdLKWxKz4WgyP6y8gs0apBisqHLVe3eQUrlXADyJsT3V4FLp+Rqh36+WNyRJsLs56UgzitS1+M=
