destination: _site/
production: true

permalink: /blog/:title/
excerpt_separator: "\n\n"

name: chrly
title: Chrly

pygments: true

# google_analytics_id:

url: http://lirsac.me/

exclude: ['readme.md', 'Gemfile', 'node_modules', '.gitignore', 'Gruntfile.js', 'Gruntfile.coffee', 'config.rb', 'package.json', 'favicon.psd', '.sass-cache', 'package.json', 'bower.json', '.bowerrc', 'bower_components', '_assets', '.jekyll']
