destination: _site/
production: true
drafts: false
future: false

permalink: /blog/:title/
excerpt_separator: "\n\n"

highlighter: 'rouge'
markdown: redcarpet
redcarpet:
    extensions: ["strikethrough", "footnotes", "underline"]

exclude: ['.travis.yml', 'readme.md', 'Gemfile', 'Gemfile.lock', 'node_modules', '.gitignore', 'Gruntfile.js', 'Gruntfile.coffee', 'config.rb', 'package.json', 'favicon.psd', '.sass-cache', 'package.json', 'bower.json', '.bowerrc', 'bower_components', '_assets', '.jekyll', 's3_website.yml', 'scss-lint-report.xml', 'gulpfile.js']

google_analytics_id: UA-36424269-1

url: http://lirsac.me/
name: Charles Lirsac
