destination: _site/
production: false

excerpt_separator: "\n\n"

permalink: /blog/:title
paginate: 8
paginate_path: page/:num

name: chrly
pygments: true

social_github: CharlesLirsac
social_twitter: lirsacc
social_linkedin: charleslirsac
# social_google-plus: CharlesLirsac
# social_email: charles@lirsac.me

# google_analytics_id:

url: http://localhost:9090/

exclude: ['node_modules', '.gitignore', 'Gruntfile.js', 'Gruntfile.coffee', 'config.rb', 'package.json', 'favicon.psd', '.sass-cache', 'package.json', 'bower.json', '.bowerrc', 'bower_components', '_assets', '.jekyll']
