title = "lirsacc"

# The URL the site will be built for
base_url = "https://lirsac.me"

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-dark"

# Whether to generate a RSS feed automatically
generate_feed = true

# Whether to generate a tags page and individual
# tag pages for pages with tags
generate_tags_pages = false

# Whether to generate a categories page and individual
# category pages for pages with a category
generate_categories_pages = false

[extra]
description = "Online home of Charles Lirsac"
author = "Charles Lirsac"

[extra.opengraph]
site_name = "lirsac.me"
email = "contact@lirsac.me"
